/* tslint:disable */
// This file is generated
// Do not edit this file

import { Messages } from './messages/index'
export * from './messages/index'

export type ChannelGroup = {
  messages: Messages
  message: { "tags": { "id": { "title": "Message ID", "description": "Message ID from Chat" } } }
  conversation: { "tags": { "id": { "title": "Conversation ID", "description": "Conversation ID from Chat" } }, "creation": { "enabled": false, "requiredTags": [] } }
}