/* tslint:disable */
// This file is generated
// Do not edit this file
import * as userRegistered from "./userRegistered";
export * as userRegistered from "./userRegistered";
import * as userAuthenticated from "./userAuthenticated";
export * as userAuthenticated from "./userAuthenticated";
import * as accountCreated from "./accountCreated";
export * as accountCreated from "./accountCreated";

export type Events = {
  userRegistered: userRegistered.UserRegistered;
  userAuthenticated: userAuthenticated.UserAuthenticated;
  accountCreated: accountCreated.AccountCreated;
}
