/* tslint:disable */
// This file is generated
// Do not edit this file
import * as text from "./text";
export * as text from "./text";
import * as choice from "./choice";
export * as choice from "./choice";

export type Messages = {
  text: text.Text;
  choice: choice.Choice;
}
