/* tslint:disable */
// This file is generated
// Do not edit this file
import * as registerUser from "./registerUser/index";
export * as registerUser from "./registerUser/index";
import * as createAccount from "./createAccount/index";
export * as createAccount from "./createAccount/index";
import * as queryAccounts from "./queryAccounts/index";
export * as queryAccounts from "./queryAccounts/index";
import * as authenticateUser from "./authenticateUser/index";
export * as authenticateUser from "./authenticateUser/index";

export type Actions = {
  registerUser: registerUser.ActionRegisterUser;
  createAccount: createAccount.ActionCreateAccount;
  queryAccounts: queryAccounts.ActionQueryAccounts;
  authenticateUser: authenticateUser.ActionAuthenticateUser;
}
