// <auto-generated />
using CuentasApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuentasApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240426231505_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("CuentasApi.Data.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountName = "Personal Loan Account",
                            AccountNumber = "26996633",
                            Balance = 638.29m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountName = "Credit Card Account",
                            AccountNumber = "58744279",
                            Balance = 561.44m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccountName = "Personal Loan Account",
                            AccountNumber = "19398505",
                            Balance = 659.70m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            AccountName = "Investment Account",
                            AccountNumber = "31770994",
                            Balance = 543.88m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            AccountName = "Investment Account",
                            AccountNumber = "49560623",
                            Balance = 973.80m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            AccountName = "Personal Loan Account",
                            AccountNumber = "63597767",
                            Balance = 292.64m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            AccountName = "Checking Account",
                            AccountNumber = "60466370",
                            Balance = 103.91m,
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            AccountName = "Auto Loan Account",
                            AccountNumber = "08082306",
                            Balance = 94.72m,
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            AccountName = "Checking Account",
                            AccountNumber = "61795975",
                            Balance = 912.53m,
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            AccountName = "Checking Account",
                            AccountNumber = "39933094",
                            Balance = 712.01m,
                            UserId = 5
                        },
                        new
                        {
                            Id = 11,
                            AccountName = "Auto Loan Account",
                            AccountNumber = "76589896",
                            Balance = 939.63m,
                            UserId = 5
                        },
                        new
                        {
                            Id = 12,
                            AccountName = "Auto Loan Account",
                            AccountNumber = "47310032",
                            Balance = 704.50m,
                            UserId = 6
                        },
                        new
                        {
                            Id = 13,
                            AccountName = "Personal Loan Account",
                            AccountNumber = "53555610",
                            Balance = 140.60m,
                            UserId = 6
                        },
                        new
                        {
                            Id = 14,
                            AccountName = "Auto Loan Account",
                            AccountNumber = "83103756",
                            Balance = 583.11m,
                            UserId = 7
                        },
                        new
                        {
                            Id = 15,
                            AccountName = "Money Market Account",
                            AccountNumber = "10473149",
                            Balance = 438.89m,
                            UserId = 7
                        },
                        new
                        {
                            Id = 16,
                            AccountName = "Savings Account",
                            AccountNumber = "42681382",
                            Balance = 481.24m,
                            UserId = 7
                        },
                        new
                        {
                            Id = 17,
                            AccountName = "Money Market Account",
                            AccountNumber = "73825063",
                            Balance = 830.79m,
                            UserId = 8
                        },
                        new
                        {
                            Id = 18,
                            AccountName = "Savings Account",
                            AccountNumber = "60967028",
                            Balance = 360.71m,
                            UserId = 8
                        },
                        new
                        {
                            Id = 19,
                            AccountName = "Savings Account",
                            AccountNumber = "61431633",
                            Balance = 380.15m,
                            UserId = 8
                        },
                        new
                        {
                            Id = 20,
                            AccountName = "Investment Account",
                            AccountNumber = "60245534",
                            Balance = 924.09m,
                            UserId = 9
                        },
                        new
                        {
                            Id = 21,
                            AccountName = "Investment Account",
                            AccountNumber = "81052956",
                            Balance = 212.24m,
                            UserId = 10
                        },
                        new
                        {
                            Id = 22,
                            AccountName = "Investment Account",
                            AccountNumber = "21930280",
                            Balance = 109.62m,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("CuentasApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cedula = "150301-6016",
                            LastName = "Barton",
                            Name = "Jenifer"
                        },
                        new
                        {
                            Id = 2,
                            Cedula = "261202-8446",
                            LastName = "Bayer",
                            Name = "Yessenia"
                        },
                        new
                        {
                            Id = 3,
                            Cedula = "160161-1275",
                            LastName = "Watsica",
                            Name = "Ayden"
                        },
                        new
                        {
                            Id = 4,
                            Cedula = "070488-4923",
                            LastName = "Renner",
                            Name = "Jovanny"
                        },
                        new
                        {
                            Id = 5,
                            Cedula = "240778-1301",
                            LastName = "Terry",
                            Name = "Philip"
                        },
                        new
                        {
                            Id = 6,
                            Cedula = "170756-1544",
                            LastName = "VonRueden",
                            Name = "Talon"
                        },
                        new
                        {
                            Id = 7,
                            Cedula = "190755-4526",
                            LastName = "Toy",
                            Name = "Filomena"
                        },
                        new
                        {
                            Id = 8,
                            Cedula = "191079-3078",
                            LastName = "Hettinger",
                            Name = "Darrion"
                        },
                        new
                        {
                            Id = 9,
                            Cedula = "050260-1814",
                            LastName = "Schumm",
                            Name = "Jay"
                        },
                        new
                        {
                            Id = 10,
                            Cedula = "160357-4687",
                            LastName = "Ratke",
                            Name = "Sage"
                        });
                });

            modelBuilder.Entity("CuentasApi.Data.Account", b =>
                {
                    b.HasOne("CuentasApi.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuentasApi.Models.User", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
