// <auto-generated />
using CuentasApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuentasApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("CuentasApi.Data.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountName = "Credit Card Account",
                            AccountNumber = "06070185",
                            Balance = 305.42m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountName = "Checking Account",
                            AccountNumber = "65279254",
                            Balance = 407.98m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccountName = "Credit Card Account",
                            AccountNumber = "77190138",
                            Balance = 883.33m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            AccountName = "Personal Loan Account",
                            AccountNumber = "27590395",
                            Balance = 882.34m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            AccountName = "Money Market Account",
                            AccountNumber = "11913637",
                            Balance = 768.33m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            AccountName = "Money Market Account",
                            AccountNumber = "61483875",
                            Balance = 124.72m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            AccountName = "Personal Loan Account",
                            AccountNumber = "89812305",
                            Balance = 833.95m,
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            AccountName = "Home Loan Account",
                            AccountNumber = "48890247",
                            Balance = 359.23m,
                            UserId = 5
                        },
                        new
                        {
                            Id = 9,
                            AccountName = "Investment Account",
                            AccountNumber = "24626670",
                            Balance = 112.15m,
                            UserId = 6
                        },
                        new
                        {
                            Id = 10,
                            AccountName = "Auto Loan Account",
                            AccountNumber = "04020096",
                            Balance = 5.80m,
                            UserId = 6
                        },
                        new
                        {
                            Id = 11,
                            AccountName = "Home Loan Account",
                            AccountNumber = "48777961",
                            Balance = 782.14m,
                            UserId = 7
                        },
                        new
                        {
                            Id = 12,
                            AccountName = "Savings Account",
                            AccountNumber = "97273917",
                            Balance = 663.58m,
                            UserId = 7
                        },
                        new
                        {
                            Id = 13,
                            AccountName = "Investment Account",
                            AccountNumber = "12530471",
                            Balance = 966.53m,
                            UserId = 7
                        },
                        new
                        {
                            Id = 14,
                            AccountName = "Savings Account",
                            AccountNumber = "01049242",
                            Balance = 499.18m,
                            UserId = 8
                        },
                        new
                        {
                            Id = 15,
                            AccountName = "Home Loan Account",
                            AccountNumber = "24166175",
                            Balance = 151.02m,
                            UserId = 8
                        },
                        new
                        {
                            Id = 16,
                            AccountName = "Savings Account",
                            AccountNumber = "23502669",
                            Balance = 884.43m,
                            UserId = 9
                        },
                        new
                        {
                            Id = 17,
                            AccountName = "Money Market Account",
                            AccountNumber = "68377044",
                            Balance = 814.19m,
                            UserId = 9
                        },
                        new
                        {
                            Id = 18,
                            AccountName = "Checking Account",
                            AccountNumber = "01673478",
                            Balance = 876.40m,
                            UserId = 9
                        },
                        new
                        {
                            Id = 19,
                            AccountName = "Money Market Account",
                            AccountNumber = "92899345",
                            Balance = 886.91m,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("CuentasApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cedula = "281276-1490",
                            Email = "Elaine_Hirthe23@hotmail.com",
                            LastName = "Bauch",
                            Name = "Dallin",
                            PhoneNumber = "592.789.6670 x508"
                        },
                        new
                        {
                            Id = 2,
                            Cedula = "190198-0892",
                            Email = "Beverly.Bogisich@hotmail.com",
                            LastName = "Ernser",
                            Name = "Quincy",
                            PhoneNumber = "(558) 736-4563 x428"
                        },
                        new
                        {
                            Id = 3,
                            Cedula = "180499-1103",
                            Email = "Guadalupe1@hotmail.com",
                            LastName = "Kris",
                            Name = "Ila",
                            PhoneNumber = "416-204-3930 x125"
                        },
                        new
                        {
                            Id = 4,
                            Cedula = "250491-0493",
                            Email = "Lance.Streich@gmail.com",
                            LastName = "Connelly",
                            Name = "Flo",
                            PhoneNumber = "(223) 416-0302"
                        },
                        new
                        {
                            Id = 5,
                            Cedula = "270370-4002",
                            Email = "Melissa_Rippin@yahoo.com",
                            LastName = "Windler",
                            Name = "Mckenzie",
                            PhoneNumber = "(854) 942-2686 x497"
                        },
                        new
                        {
                            Id = 6,
                            Cedula = "270359-3790",
                            Email = "Beverly_Hansen@hotmail.com",
                            LastName = "Miller",
                            Name = "Lucio",
                            PhoneNumber = "1-932-897-5988"
                        },
                        new
                        {
                            Id = 7,
                            Cedula = "230467-0021",
                            Email = "Gabriel.Bode@yahoo.com",
                            LastName = "Becker",
                            Name = "Dawn",
                            PhoneNumber = "1-846-887-7283 x319"
                        },
                        new
                        {
                            Id = 8,
                            Cedula = "190495-1680",
                            Email = "Maxine_DuBuque93@gmail.com",
                            LastName = "Keebler",
                            Name = "Krista",
                            PhoneNumber = "444.252.0146"
                        },
                        new
                        {
                            Id = 9,
                            Cedula = "011171-3545",
                            Email = "Noel.Kilback@gmail.com",
                            LastName = "Mante",
                            Name = "Myrtie",
                            PhoneNumber = "465.400.0027"
                        },
                        new
                        {
                            Id = 10,
                            Cedula = "150961-2974",
                            Email = "Jody21@gmail.com",
                            LastName = "Kulas",
                            Name = "Julian",
                            PhoneNumber = "228.452.1473"
                        });
                });

            modelBuilder.Entity("CuentasApi.Data.Account", b =>
                {
                    b.HasOne("CuentasApi.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuentasApi.Models.User", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
